Get-appxpackage -allusers *bing* | Remove-AppxPackage
Get-appxpackage -allusers *zune* | Remove-AppxPackage
Get-appxpackage -allusers *oneconne* | Remove-AppxPackage
Get-appxpackage -allusers *soundrecorder* | Remove-AppxPackage
Get-appxpackage -allusers *Office* | Remove-AppxPackage
Get-appxpackage -allusers *phone* | Remove-AppxPackage
Get-appxpackage -allusers *ConnectivityStore* | Remove-AppxPackage
Get-appxpackage -allusers *Messaging* | Remove-AppxPackage
Get-appxpackage -allusers *windowsmaps* | Remove-AppxPackage
Get-appxpackage -allusers *getstarted* | Remove-AppxPackage
Get-appxpackage -allusers *skypeapp* | Remove-AppxPackage
Get-appxpackage -allusers *windowscamera* | Remove-AppxPackage
Get-appxpackage -allusers *windowscommunicationsapps* | Remove-AppxPackage
Get-appxpackage -allusers *windowsalarms* | Remove-AppxPackage
Get-appxpackage -allusers *3dbuilder* | Remove-AppxPackage
Get-appxpackage -allusers *Microsoft.People* | Remove-AppxPackage
Get-appxpackage -allusers *solitairecollection* | Remove-AppxPackage
Get-appxpackage -allusers *xboxapp* | Remove-AppxPackage
Get-appxpackage -allusers *WindowsFeedbackHub* | Remove-AppxPackage
Get-appxpackage -allusers *GetHelp* | Remove-AppxPackage
Get-appxpackage -allusers *WindowsCamera* | Remove-AppxPackage
